FROM nginx:1.14.2

# install some handy utilities.  do this early in docker so they are cached in a layer
RUN \
  apt-get update \
  && apt-get install -y curl \
  && apt-get install -y nano \
  && apt-get install -y git


# install node in another early layer so it can be cached
ENV NODE_VERSION v10.13.0
# download and install node
RUN curl -SLO https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-linux-x64.tar.gz
RUN tar -xzf "node-$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1
RUN ln -s /usr/local/bin/node /usr/local/bin/nodejs

ENV ANGULAR_CLI @angular/cli@10.2.3
RUN npm install -g $ANGULAR_CLI


